### ISSUE TITLE
Calbot reminder spam

### ISSUE THREAD

**Issue by gsouquet** [erikjohnston/calendar_bot#20]
Calbot has suddenly posted around 5 reminder per second in a room.

<img width="712" alt="Screenshot 2023-03-29 at 10 00 47" src="https://user-images.githubusercontent.com/769871/228483696-2fc4b776-6643-42ba-b872-d6647c215f78.png">

Room ID: `!NzAZZSQzNMFnFvKCKn:element.io`

**Comment by erikjohnston** [comment]
Fixed by https://github.com/erikjohnston/calendar_bot/commit/6ee2a23106ecac4eaade05f58fee13511ba0058e
